/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and kept in source control so typechecking
// works immediately in fresh development environments.
